/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWaterRouteImport } from './routes/_app/water'
import { Route as AppStepsRouteImport } from './routes/_app/steps'
import { Route as AppSavedRouteImport } from './routes/_app/saved'
import { Route as AppRemindersRouteImport } from './routes/_app/reminders'
import { Route as AppRecipesRouteImport } from './routes/_app/recipes'
import { Route as AppProgressRouteImport } from './routes/_app/progress'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppMealPlanRouteImport } from './routes/_app/meal-plan'
import { Route as AppIngredientsRouteImport } from './routes/_app/ingredients'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppContactRouteImport } from './routes/_app/contact'
import { Route as AppCaloriesRouteImport } from './routes/_app/calories'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppRecipesIdRouteImport } from './routes/_app/recipes.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWaterRoute = AppWaterRouteImport.update({
  id: '/water',
  path: '/water',
  getParentRoute: () => AppRoute,
} as any)
const AppStepsRoute = AppStepsRouteImport.update({
  id: '/steps',
  path: '/steps',
  getParentRoute: () => AppRoute,
} as any)
const AppSavedRoute = AppSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AppRoute,
} as any)
const AppRemindersRoute = AppRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesRoute = AppRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMealPlanRoute = AppMealPlanRouteImport.update({
  id: '/meal-plan',
  path: '/meal-plan',
  getParentRoute: () => AppRoute,
} as any)
const AppIngredientsRoute = AppIngredientsRouteImport.update({
  id: '/ingredients',
  path: '/ingredients',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppContactRoute = AppContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AppRoute,
} as any)
const AppCaloriesRoute = AppCaloriesRouteImport.update({
  id: '/calories',
  path: '/calories',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesIdRoute = AppRecipesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppRecipesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AppAdminRoute
  '/calories': typeof AppCaloriesRoute
  '/contact': typeof AppContactRoute
  '/dashboard': typeof AppDashboardRoute
  '/ingredients': typeof AppIngredientsRoute
  '/meal-plan': typeof AppMealPlanRoute
  '/profile': typeof AppProfileRoute
  '/progress': typeof AppProgressRoute
  '/recipes': typeof AppRecipesRouteWithChildren
  '/reminders': typeof AppRemindersRoute
  '/saved': typeof AppSavedRoute
  '/steps': typeof AppStepsRoute
  '/water': typeof AppWaterRoute
  '/recipes/$id': typeof AppRecipesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AppAdminRoute
  '/calories': typeof AppCaloriesRoute
  '/contact': typeof AppContactRoute
  '/dashboard': typeof AppDashboardRoute
  '/ingredients': typeof AppIngredientsRoute
  '/meal-plan': typeof AppMealPlanRoute
  '/profile': typeof AppProfileRoute
  '/progress': typeof AppProgressRoute
  '/recipes': typeof AppRecipesRouteWithChildren
  '/reminders': typeof AppRemindersRoute
  '/saved': typeof AppSavedRoute
  '/steps': typeof AppStepsRoute
  '/water': typeof AppWaterRoute
  '/recipes/$id': typeof AppRecipesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/calories': typeof AppCaloriesRoute
  '/_app/contact': typeof AppContactRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/ingredients': typeof AppIngredientsRoute
  '/_app/meal-plan': typeof AppMealPlanRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/progress': typeof AppProgressRoute
  '/_app/recipes': typeof AppRecipesRouteWithChildren
  '/_app/reminders': typeof AppRemindersRoute
  '/_app/saved': typeof AppSavedRoute
  '/_app/steps': typeof AppStepsRoute
  '/_app/water': typeof AppWaterRoute
  '/_app/recipes/$id': typeof AppRecipesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/admin'
    | '/calories'
    | '/contact'
    | '/dashboard'
    | '/ingredients'
    | '/meal-plan'
    | '/profile'
    | '/progress'
    | '/recipes'
    | '/reminders'
    | '/saved'
    | '/steps'
    | '/water'
    | '/recipes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/admin'
    | '/calories'
    | '/contact'
    | '/dashboard'
    | '/ingredients'
    | '/meal-plan'
    | '/profile'
    | '/progress'
    | '/recipes'
    | '/reminders'
    | '/saved'
    | '/steps'
    | '/water'
    | '/recipes/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/_app/admin'
    | '/_app/calories'
    | '/_app/contact'
    | '/_app/dashboard'
    | '/_app/ingredients'
    | '/_app/meal-plan'
    | '/_app/profile'
    | '/_app/progress'
    | '/_app/recipes'
    | '/_app/reminders'
    | '/_app/saved'
    | '/_app/steps'
    | '/_app/water'
    | '/_app/recipes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/water': {
      id: '/_app/water'
      path: '/water'
      fullPath: '/water'
      preLoaderRoute: typeof AppWaterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/steps': {
      id: '/_app/steps'
      path: '/steps'
      fullPath: '/steps'
      preLoaderRoute: typeof AppStepsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saved': {
      id: '/_app/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AppSavedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reminders': {
      id: '/_app/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof AppRemindersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recipes': {
      id: '/_app/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof AppRecipesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/progress': {
      id: '/_app/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meal-plan': {
      id: '/_app/meal-plan'
      path: '/meal-plan'
      fullPath: '/meal-plan'
      preLoaderRoute: typeof AppMealPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ingredients': {
      id: '/_app/ingredients'
      path: '/ingredients'
      fullPath: '/ingredients'
      preLoaderRoute: typeof AppIngredientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contact': {
      id: '/_app/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof AppContactRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calories': {
      id: '/_app/calories'
      path: '/calories'
      fullPath: '/calories'
      preLoaderRoute: typeof AppCaloriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recipes/$id': {
      id: '/_app/recipes/$id'
      path: '/$id'
      fullPath: '/recipes/$id'
      preLoaderRoute: typeof AppRecipesIdRouteImport
      parentRoute: typeof AppRecipesRoute
    }
  }
}

interface AppRecipesRouteChildren {
  AppRecipesIdRoute: typeof AppRecipesIdRoute
}

const AppRecipesRouteChildren: AppRecipesRouteChildren = {
  AppRecipesIdRoute: AppRecipesIdRoute,
}

const AppRecipesRouteWithChildren = AppRecipesRoute._addFileChildren(
  AppRecipesRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppCaloriesRoute: typeof AppCaloriesRoute
  AppContactRoute: typeof AppContactRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppIngredientsRoute: typeof AppIngredientsRoute
  AppMealPlanRoute: typeof AppMealPlanRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProgressRoute: typeof AppProgressRoute
  AppRecipesRoute: typeof AppRecipesRouteWithChildren
  AppRemindersRoute: typeof AppRemindersRoute
  AppSavedRoute: typeof AppSavedRoute
  AppStepsRoute: typeof AppStepsRoute
  AppWaterRoute: typeof AppWaterRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppCaloriesRoute: AppCaloriesRoute,
  AppContactRoute: AppContactRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppIngredientsRoute: AppIngredientsRoute,
  AppMealPlanRoute: AppMealPlanRoute,
  AppProfileRoute: AppProfileRoute,
  AppProgressRoute: AppProgressRoute,
  AppRecipesRoute: AppRecipesRouteWithChildren,
  AppRemindersRoute: AppRemindersRoute,
  AppSavedRoute: AppSavedRoute,
  AppStepsRoute: AppStepsRoute,
  AppWaterRoute: AppWaterRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
